version: "3.3"
services:

  spark-master:
    image: final:latest
    ports:
      - "9090"
      - "7077"
      - "8888"
      - "4040"
      - "8000"
      - "9191"
    volumes:
       - /home/ubuntu-user/spark_cluster_1_no_hadoop:/home
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    restart: always
  spark-worker-a:
    image: final:latest
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
