version: "3.3"
services:
  app:
    build:
        context: .
    ports:
        -  "8888"
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - app
    ports:
      - "9191:80"

  spark-master:
    image: trabajo_final:latest
    ports:
      - "9090:8080"
      - "7077:7077"
      - "8888:8888"
      - "4040:4040"
      - "8000:8000"
      - "9191:9191"
      - "9292:9292"
    volumes:
       - /home/ubuntu-user/spark_cluster_1_no_hadoop:/home
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    restart: always
  spark-worker-a:
    image: trabajo_final:latest
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - /home/ubuntu-user/spark_cluster_1_no_hadoop:/home
    restart: always
  spark-worker-b:
    image: trabajo_final:latest
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - /home/ubuntu-user/spark_cluster_1_no_hadoop:/home
    restart: always