# Use the official NGINX image as the base image
FROM nginx:latest

# Remove the default NGINX configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom NGINX configuration file to container
COPY nginx.conf /etc/nginx/conf.d/

# Expose port 80
EXPOSE 80
